version: '3.8'
services:
  ISAAC-floor-database:
    image: mysql
    networks:
      - ISAAC-network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      
 networks:
  ISAAC-network:     
