# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Create env file
      run: |
        touch .env
        echo DB_HOST= ${{ secrets.DB_HOST }} >> .env
        echo DB_USER= ${{ secrets.DB_USER }} >> .env
        echo DB_PASSWORD= ${{ secrets.DB_PASSWORD }} >> .env
        echo DB_DATABASE= ${{ secrets.DB_DATABASE }} >> .env
        echo DB_PORT= ${{ secrets.DB_PORT }} >> .env
        echo DB_DIALECT= ${{ secrets.DB_DIALECT }} >> .env
        echo PORT= ${{ secrets.PORT }} >> .env
        echo DB_DATABASE_TEST= ${{ secrets.DB_DATABASE_TEST }} >> .env
        cat .env
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      env: 
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DIALECT: mysql
        PORT: ${{ secrets.PORT }}
        DB_DATABASE_TEST: ${{ secrets.DB_DATABASE_TEST }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
